name: Deployement pipeline 

on: 
    push:
      branches:
        - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs: 
    build_and_test:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: '24'
            
            - name: install frontdep
              run: cd frontend && npm i
            - name: test frontend
              run: cd frontend && npm run test
            - name: prod build frontend
              run: cd frontend && npm run build
            - name: install server dependencies 
              run: npm ci
            - name: test server 
              env:
               TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
               SECRET: ${{ secrets.SECRET }}
               PORT: ${{ secrets.PORT }}

              run: npm run test:server
            - name: Install playwright browser
              run: npx playwright install --with-deps
            - name: run playwright test 
              env:
               TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
               SECRET: ${{ secrets.SECRET }}
               PORT: ${{ secrets.PORT }}
               
              run: npm run test 


    deploy:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - name: Deploy
          if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')
          env:
            render_hook: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
           curl "$render_hook"
    notify_failure: 
      needs: [build_and_test,deploy]
      runs-on: ubuntu-latest
      if: | 
          needs.deploy.result == 'failure' ||
          needs.build_and_test.result == 'failure' ||
          needs.deploy.result == 'cancelled' ||
          needs.build_and_test.result == 'cancelled' 

      steps:
      - name: Find failed jobs
        id: failed_jobs
        run: |
          echo '${{ toJson(needs) }}' > needs.json

          FAILED_JOBS=$(jq -r '
            to_entries
            | map(select(.value.result == "failure" or .value.result == "cancelled"))
            | .[].key
          ' needs.json | paste -sd ", " -)

          echo "failed_jobs=$FAILED_JOBS" >> $GITHUB_OUTPUT

      - name: err_msg 
        uses: sarisia/actions-status-discord@v1

        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true
          username: Fullstack part 11 Hook
          content: " :x: Build failed! The pipeline encountered an error"
          title: "Failure details"
          description: |
            **Repo**: `${{ github.repository }}`
            **Branch**: `${{ github.ref_name }}`
            **Commit**: `${{ github.sha }}`
            **Message**: `${{ github.event.commits[0].message }}`
            **Author**: `${{ github.event.commits[0].author.name }}`
            **Workflow**: `${{ github.workflow }}`
            **Job**: `${{ steps.failed_jobs.outputs.failed_jobs }}`

            [View Commit](${{ github.event.commits[0].url }})
            [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}})

          image: ${{ secrets.EMBED_IMAGE }}
          color: 0xff0000
    notify_success: 
      needs: [deploy]
      runs-on: ubuntu-latest
      
      steps:
      - name: success_msg
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true
          username: Fullstack part 11 Hook
          color: 0x00ff00
          content: ":white_check_mark:  Deployement Successful! A new version deployed to production"
          title: "Deployement Details"
          description: | 
            **Commit**: `${{ github.sha }}`
            **Message**: `${{ github.event.commits[0].message }}`
            **Author**: `${{ github.event.commits[0].author.name }}`

          url: "https://github.com/sarisia/actions-status-discord"
          avatar_url: ${{ secrets.AVATAR_URL }}
    tag_release:
      needs: [deploy]
      runs-on: ubuntu-latest

      if: ${{ contains( join( github.event.commits.*.message, ', '), '#skip' ) == false }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}